# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=30)),
                ('descripcion_evento', models.CharField(max_length=200)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('img', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=20)),
                ('direccion_local', models.CharField(max_length=200)),
                ('nombre_propietario', models.CharField(max_length=60)),
                ('telefono_local', models.CharField(max_length=15)),
                ('celular_local', models.CharField(max_length=12)),
                ('email_local', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Local'),
        ),
        migrations.AddField(
            model_name='categoriaeventos',
            name='eventos',
            field=models.ManyToManyField(to='events.Evento'),
        ),
    ]
