# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEvento',
            fields=[
                ('cod_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'CatEvento',
                'verbose_name_plural': 'CatEventos',
                'default_related_name': 'CatEvento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('cod_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=30)),
                ('descripcion_evento', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('familiar', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('img', models.CharField(max_length=300)),
                ('categorias_eventos', models.ManyToManyField(related_name='Evento', to='events.CatEvento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'default_related_name': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('cod_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('direccion_local', models.CharField(max_length=200)),
                ('nombre_propietario', models.CharField(max_length=60)),
                ('telefono_local', models.CharField(max_length=15)),
                ('celular_local', models.CharField(max_length=12)),
                ('email_local', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'default_related_name': 'Local',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Evento', to='events.Local'),
        ),
    ]
