# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaeventos',
            name='eventos',
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias_eventos',
            field=models.ManyToManyField(to='events.CategoriaEventos'),
        ),
    ]
