# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='categorias_eventos',
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre_categoria',
            field=models.CharField(choices=[('M', 'Musica'), ('T', 'Teatro'), ('G', 'Gaming'), ('P', 'Politica'), ('D', 'Deportes'), ('F', 'Farra')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion_evento',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitud_evento',
            field=models.CharField(default='-3.984197', max_length=15),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud_evento',
            field=models.CharField(default='-79.200370', max_length=15),
        ),
        migrations.DeleteModel(
            name='CatEvento',
        ),
    ]
