# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180320_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='direccion_evento',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
