# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171017_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaeventos',
            options={'verbose_name': 'Categoria Evento', 'verbose_name_plural': 'Categoria Eventos'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='categorias_eventos',
            field=models.ManyToManyField(related_name='Eventos', to='events.CategoriaEventos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='events.Local'),
        ),
    ]
