# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171018_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
