# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_local_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_evento',
        ),
    ]
