# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_evento_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categorias_eventos',
            field=models.ManyToManyField(to='events.CategoriaEventos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Local'),
        ),
    ]
