# Generated by Django 2.2 on 2019-04-17 02:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'default_related_name': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=100)),
                ('calle_secundaria', models.CharField(max_length=100)),
                ('refencia', models.CharField(max_length=100)),
                ('latitud', models.CharField(default='-3.984197', max_length=15)),
                ('longitud', models.CharField(default='-79.200370', max_length=15)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'default_related_name': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('nombre_propietario', models.CharField(max_length=60)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.CharField(default='img.png', max_length=300)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='eventHandler.Calificacion')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='eventHandler.Direccion')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'default_related_name': 'local',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('familiar', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('image', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('M', 'Musica'), ('T', 'Teatro'), ('G', 'Gaming'), ('P', 'Politica'), ('D', 'Deportes'), ('F', 'Farra')], default='F', max_length=2)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventHandler.Calificacion')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventHandler.Direccion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventHandler.Local')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'default_related_name': 'evento',
            },
        ),
    ]
