# Generated by Django 2.2 on 2019-04-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='local',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='eventHandler.Evento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='eventHandler.Local'),
        ),
    ]
