# Generated by Django 2.2 on 2019-04-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventHandler', '0003_calificacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='eventHandler.Evento'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='eventHandler.Local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='image',
            field=models.CharField(default='img.png', max_length=300),
        ),
    ]
